const char *MenuStyles[] = {
        "verticalGradient",
};

typedef enum {
    VERTICAL_GRADIENT,
} MenuStyle;

typedef enum {
    PARTY_MENU,
    ITEMS_MENU,
    MAGIC_MENU,
    PARTY_APPLY_MENU,
    PARTY_SELECT_MENU,
    LOAD_MENU,
    SAVE_MENU,
    QUIT_MENU,
    ACKNOWLEDGE_MENU,
    BEAST_LIST_FIGHT_MENU,
    BEAST_TARGET_FIGHT_MENU,
    MOBILE_SELECT_FIGHT_MENU,
    MOBILE_TARGET_FIGHT_MENU,
    ACTION_SELECT_FIGHT_MENU,
    MAGIC_FIGHT_MENU,
    ITEMS_FIGHT_MENU,
    SHOP_WELCOME_MENU,
    SHOP_BUY_MENU,
    SHOP_SELL_MENU,
    SHOP_GOODBYE_MENU,
} MenuType;
