const char *MenuStyles[] = {
        "verticalGradient",
};

typedef enum {
    VERTICAL_GRADIENT,
} MenuStyle;

typedef enum {
    MAIN_MENU,
    SETTINGS_MENU,
    SETTINGS_FULL_SCREEN_MENU,
    SETTINGS_DIFFICULTY_MENU,
    SETTINGS_RESOLUTION_MENU,
    PARTY_MENU,
    ITEMS_MENU,
    MAGIC_MENU,
    PARTY_APPLY_MENU,
    PARTY_SELECT_MENU,
    LOAD_SAVE_MENU,
    QUIT_GAME_MENU,
    ACKNOWLEDGE_SAVE_MENU,
    BEAST_LIST_FIGHT_MENU,
    BEAST_TARGET_FIGHT_MENU,
    MOBILE_SELECT_FIGHT_MENU,
    MOBILE_TARGET_FIGHT_MENU,
    ACTION_SELECT_FIGHT_MENU,
    MAGIC_FIGHT_MENU,
    ITEMS_FIGHT_MENU,
    SHOP_WELCOME_MENU,
    SHOP_BUY_MENU,
    SHOP_SELL_MENU,
    SHOP_CANNOT_AFFORD_MENU,
    SHOP_QUANTITY_BUY_MENU,
    SHOP_QUANTITY_SELL_MENU,
    SHOP_CONFIRM_PURCHASE_MENU,
    SHOP_CONFIRM_SALE_MENU,
} MenuType;
