#ifndef CJRPGENGINE_CONSTANTS_H
#define CJRPGENGINE_CONSTANTS_H

#define MAX_VITALS_LENGTH 14
#define MAX_STORIES 1024
#define MAX_SPELLS 256
#define MAX_ITEMS 256
#define MAX_ACTION_GAUGE 300
#define MOB_COLLISION_WIDTH 12
#define MOB_COLLISION_WIDTH_OFFSET 2
#define MOB_COLLISION_HEIGHT 12
#define MOB_COLLISION_HEIGHT_OFFSET 12

#endif //CJRPGENGINE_CONSTANTS_H
