#ifndef CJRPGENGINE_CONTROL_H
#define CJRPGENGINE_CONTROL_H

#define MAX_CONTROLS 255
#define MAX_ACTIVE_CONTROLS 64
#define MAX_INSTRUCTIONS 255

#include "control.c"

#endif //CJRPGENGINE_CONTROL_H
