//
// Created by Dan Munro on 9/5/23.
//

#ifndef CJRPGENGINE_EXPLORATION_H
#define CJRPGENGINE_EXPLORATION_H

#define MAX_EXITS 64
#define MAX_ENTRANCES 64
#define MAX_ARRIVE_AT 64

#define MAX_MOBILES 255
#define MAX_MOBILE_MOVEMENTS 64

#define MAX_OBJECTS 255

#define MOB_COLLISION_WIDTH 12
#define MOB_COLLISION_WIDTH_OFFSET 2
#define MOB_COLLISION_HEIGHT 12
#define MOB_COLLISION_HEIGHT_OFFSET 12

#endif //CJRPGENGINE_EXPLORATION_H
