#ifndef CJRPGENGINE_FIGHT_H
#define CJRPGENGINE_FIGHT_H

#define MAX_BEASTS 255
#define MAX_BEASTS_IN_FIGHT 9
#define MAX_BEAST_NAMES_IN_FIGHT 6

#define MAX_CURSORS 64
#define MAX_ACTION_GAUGE_RAISE 10

#define MAX_ACTIONS 256

#define STEP_OUT_TIMEOUT_MS 300
#define ACTION_TIMEOUT_MS 100
#define RETURN_TIMEOUT_MS 300
#define RUN_TIMEOUT_MS 800

#define HIT_ANIMATION_TIMER_MS 300

#include "fight.c"

#endif //CJRPGENGINE_FIGHT_H
