#ifndef CJRPGENGINE_GLOBALS_H
#define CJRPGENGINE_GLOBALS_H

#define MAX_FS_PATH_LENGTH 255
#define MAX_VITALS_LENGTH 14
#define MAX_AUDIO 1024
#define MAX_SPRITES 1024

#endif //CJRPGENGINE_GLOBALS_H
