#ifndef CJRPGENGINE_GLOBALS_H
#define CJRPGENGINE_GLOBALS_H

#define MILLISECONDS_IN_SECOND 1000.0
#define MAX_FS_PATH_LENGTH 256
#define MAX_VITALS_LENGTH 14
#define MAX_SPRITES 1024
#define MAX_STORIES 1024
#define MAX_SPELLS 256
#define MAX_ITEMS 256
#define MAX_SAVE_NAME 256
#define SPELL_COLUMN_WIDTH 20
#define MAX_ACTION_GAUGE 300
#define MOB_COLLISION_WIDTH 12
#define MOB_COLLISION_WIDTH_OFFSET 2
#define MOB_COLLISION_HEIGHT 12
#define MOB_COLLISION_HEIGHT_OFFSET 12

typedef enum {
    ATTACK,
    CAST,
    ITEM,
    RUN,
    NONE,
} ActionType;

typedef enum {
    STEP_NONE,
    ATTACK_QUEUE,
    ATTACK_STEP_OUT,
    ATTACK_ACTION,
    ATTACK_RETURN,
    ACTION_STEP_RUN,
} ActionStep;

#endif //CJRPGENGINE_GLOBALS_H
