#ifndef CJRPGENGINE_GLOBALS_H
#define CJRPGENGINE_GLOBALS_H

#define MAX_FS_PATH_LENGTH 255
#define MAX_VITALS_LENGTH 14
#define MAX_AUDIO 1024
#define MAX_SPRITES 1024
#define MAX_STORIES 1024
#define STARTING_HP 20
#define STARTING_MANA 10
#define MAX_SPELLS 255
#define MAX_ITEMS 255
#define MAX_SAVE_NAME 255
#define SPELL_COLUMN_WIDTH 20
#define MAX_DATETIME_LENGTH 255
#define MAX_EQUIPMENT 4
#define MILLISECONDS_IN_SECOND 1000.0

#endif //CJRPGENGINE_GLOBALS_H
