#ifndef CJRPGENGINE_NOTIFICATION_H
#define CJRPGENGINE_NOTIFICATION_H

#define MAX_NOTIFICATIONS 64
#define MAX_NOTIFICATION_LENGTH 64

#define NOTIFICATION_DECAY_SECONDS 5
#define NOTIFICATION_HEIGHT 75
#define NOTIFICATION_WIDTH 300

typedef enum {
    RECEIVE_QUEST_ITEM,
    LOSE_QUEST_ITEM,
    RECEIVE_EXPERIENCE,
    RECEIVE_GOLD,
    LOSE_GOLD,
    SAVED,
    FIGHT_ACTION,
} NotificationType;

#include "notification.c"

#endif //CJRPGENGINE_NOTIFICATION_H
