#ifndef CJRPGENGINE_PLAYER_H
#define CJRPGENGINE_PLAYER_H

#define MAX_PARTY_SIZE 4
#define MAX_DATETIME_LENGTH 256
#define MAX_SAVE_NAME 256
#define MAX_STORIES 1024

#include "player.c"

#endif //CJRPGENGINE_PLAYER_H
