#ifndef CJRPGENGINE_EXIT_H
#define CJRPGENGINE_EXIT_H

#define EXIT_NO_INDEX_DIR 1
#define EXIT_MENU_NOT_DEFINED 100
#define EXIT_MENU_STYLE_NOT_DEFINED 101
#define EXIT_MOBILE_NOT_FOUND 200
#define EXIT_FORCE_NEW_AND_LOAD_SAVE 300
#define EXIT_FONT_STYLE_NOT_FOUND 400
#define EXIT_TEXT_BOX_NOT_FOUND 401
#define EXIT_UNABLE_TO_CREATE_SPELL 500
#define EXIT_UNABLE_TO_FIND_SPELL 501
#define EXIT_UNKNOWN_INTENT 600

#endif //CJRPGENGINE_EXIT_H
