#ifndef CJRPGENGINE_PLAYER_H
#define CJRPGENGINE_PLAYER_H

#define MAX_PARTY_SIZE 4
#define MAX_SAVE_FILES 255
#define MAX_SAVE_NAME 255
#define MAX_DATETIME_LENGTH 255
#define MAX_SPELLS 256

#endif //CJRPGENGINE_PLAYER_H
