name: Run Tests
on:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt-get update -y
      - run: |
          sudo apt-get install -y libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev \
                                  libglu1-mesa-dev freeglut3-dev mesa-common-dev build-essential
      - uses: actions/checkout@v3
      - uses: jwlawson/actions-setup-cmake@v1.13
      - run: cmake .
      - run: make
      - run: ./build/tests